// Generated by tools/build-examples.mjs — do not edit by hand.
// Scans Examples/<Category>/*.json and lists them here so the Examples
// dropdown can fetch them at runtime without a directory listing (this is a
// static site). Re-run the generator after adding/removing/renaming a file
// under Examples/.
export const examples = [
  {
    "group": "Optics Bench",
    "name": "Mach–Zehnder interferometer",
    "path": "../Examples/Optics%20Bench/Mach%E2%80%93Zehnder%20interferometer.json"
  },
  {
    "group": "Optics Bench",
    "name": "Michelson interferometer",
    "path": "../Examples/Optics%20Bench/Michelson%20interferometer.json"
  }
];
