// Auto-generated by tools/build-wiki.mjs from wiki-content.mjs — do not edit by hand.
// Lists every component type that has a built page under wiki/, so the inspector
// can avoid linking to a page that doesn't exist yet.
export const WIKI_TYPES = new Set(["aom","bs","cmirror","cmirrorx","cwlaser","detector","dichroic","diffuser","etalon","filter","freeglass","galvo","glassrod","grating","lens","lensc","lensgroup","mirror","oap","objective","polarizer","prism","pulsedlaser","retroreflector","sclaser","telescope","thicklens","vipa"]);
