// Generated by tools/build-community.mjs — do not edit by hand.
// Lists every merged community-submissions/*.json entry so the "From the community"
// dropdown can fetch them at runtime without a directory listing (this is a
// static site). The publishing workflow regenerates this file after approval.
export const community = [
  {
    "slug": "nif-one-shot-from-master-oscillator-to-target",
    "name": "NIF — one shot from master oscillator to target",
    "path": "../community-submissions/pr-42.json"
  },
  {
    "slug": "optical-spectrometer",
    "name": "Optical spectrometer",
    "path": "../community-submissions/issue-38.json"
  },
  {
    "slug": "component-library-showcase",
    "name": "Component library showcase",
    "path": "../community-submissions/issue-33.json"
  },
  {
    "slug": "bright-field-microscope",
    "name": "Bright field microscope",
    "path": "../community-submissions/issue-29.json"
  },
  {
    "slug": "laserpecker-4-dual-laser-optical-path",
    "name": "LaserPecker 4 dual-laser optical path",
    "path": "../community-submissions/issue-25.json"
  }
];
